{% set name = "pyscicat" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d4/a3/d74774d9b80f9c84a0906bf1850e1210940198da9e6d0dd7b7be969acbd6/pyscicat-0.{{ version }}.tar.gz
  sha256: 41fac550e1d8f5d31d620ba784cf5424670660c423121b4d852e7de4ae467db2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic
    - python >=3.7
    - requests

test:
  imports:
    - pyscicat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scicatproject/pyscicat
  summary: Code for communicating to a SciCat backend server python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://scicatproject.github.io/pyscicat/
  description: An API to upload data into Scicat. If using Scicat version 3, you will need to use pyscicat < 0.4.1 , if using Scicat v4 please use latest release.
extra:
  recipe-maintainers:
    - lashemilt
    - abigailalexander
    - RFIMarvin
