{% set name = "pyscicat" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/30/cf/0eedabc21c5b07ce6c946b0bdfc89b64abbafbad0215f09743ede50d5d14/pyscicat-{{ version }}.tar.gz
  sha256: cf303a92cee65c3d53a7fd0a7fa0750e5c7ae7e9acd8f64069ddd6fb37745504

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pydantic
    - python >={{ python_min }}
    - requests

test:
  imports:
    - pyscicat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scicatproject/pyscicat
  summary: Code for communicating to a SciCat backend server python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://scicatproject.github.io/pyscicat/
  description: An API to upload data into Scicat. If using Scicat version 3, you will need to use pyscicat < 0.4.1 , 
               if using Scicat v4 please use latest release.
extra:
  recipe-maintainers:
    - lashemilt
    - abigailalexander
    - RFIMarvin
